[package]
name = "wland-client"
version = "0.1.0"
authors = ["aizichen <1098679804@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
